### ISSUE TITLE
[BUG]: hidden channels error upon startup

### ISSUE THREAD

**Issue by EnderNon** [c10udburst-discord/Aliucord-RightNow-Plugins#16]
### Description of the bug

java.lang.NullPointerException
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.aliucord.PluginManager.loadPlugin(PluginManager.java:76)
	at com.aliucord.Main.loadAllPlugins(Main.java:315)
	at com.aliucord.Main.preInitWithPermissions(Main.java:86)
	at com.aliucord.Main.preInit(Main.java:73)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.aliucord.injector.InjectorKt.init(Injector.kt:115)
	at com.aliucord.injector.InjectorKt.access$init(Injector.kt:1)
	at com.aliucord.injector.InjectorKt$init$1.beforeHookedMethod(Injector.kt:43)
	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:352)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Activity.performCreate(Activity.java:8310)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1323)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4049)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4286)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:93)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2524)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:8689)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)

### Steps To Reproduce

1) start aliucord with this plugin

### Additional Information

java.lang.NullPointerException
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.aliucord.PluginManager.loadPlugin(PluginManager.java:76)
	at com.aliucord.Main.loadAllPlugins(Main.java:315)
	at com.aliucord.Main.preInitWithPermissions(Main.java:86)
	at com.aliucord.Main.preInit(Main.java:73)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.aliucord.injector.InjectorKt.init(Injector.kt:115)
	at com.aliucord.injector.InjectorKt.access$init(Injector.kt:1)
	at com.aliucord.injector.InjectorKt$init$1.beforeHookedMethod(Injector.kt:43)
	at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:352)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Activity.performCreate(Activity.java:8310)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1323)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4049)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4286)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:93)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2524)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:8689)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)

**Comment by C10udburst** [comment]
fixed

**Comment by C10udburst** [comment]
wait, no this isn't even the right version. This is hidden channels for react native version.

what you're showing is for the old kotlin version.

**Comment by EnderNon** [comment]
> This is hidden channels for react native version.

wait what? there's a react native aliucord?
